name: Package tests with Conda environment

on: 
  pull_request:
  push:


jobs:
  setup_env:
    name: Setup environment and run tests
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install -r requirements.txt
          python np_conv/test_conv2d.py
          
