name: Conv3d  tests 

on: 
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and run testsss
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
        python np_conv/test_conv3d.py
